<?php
return [
    'Permission' => [
        'dashboard',
        'user.view',
        'user.create',
        'user.edit',
        'user.delete',
        'user.profile',
        'user.setting',
        'permission.view',
        'permission.assign',
        'order.view',
        'order.edit',
        'order.delete',
        'order.place',
        'product.view',
        'product.create',
        'product.edit',
        'product.delete',
        'category.view',
        'category.create',
        'category.edit',
        'category.delete',
        'discount.view',
        'discount.create',
        'discount.edit',
        'discount.delete',
        'report.view',
        'customer.view',
        'customer.create',
        'customer.edit',
        'customer.delete',
        'auth.change_password',
        'auth.register',
        'auth.login',
        'wishlist',
        'notification.view',
        'notification.send',
        'notification.delete',
        'feedback.view',
        'feedback.reply',
        'pay.payment'

    ],
    'Description' =>[
        'Trang quản trị',
        'Xem danh sách người dùng',
        'Thêm người dùng mới',
        'Chỉnh sửa thôgn tin người dùng',
        'Xóa người dùng',
        'Chỉnh sửa hồ sơ cá nhân',
        'Cài đặt',
        'Xem danh sách quyền',
        'Cấp quyền cho người dùng',
        'Xem danh sách đơn hàng',
        'Cập nhật trạng thái đơn hàng',
        'Hủy đơn hàng',
        'Đặt hàng',
        'Xem danh sách sản phẩm',
        'Thêm sản phẩm mới',
        'Chỉnh sửa sản phẩm',
        'Xóa sản phẩm',
        'Xem danh mục loại sản phẩm',
        'Thêm loại sản phẩm',
        'Chỉnh sửa loại sản phẩm',
        'Xóa loại sản phẩm',
        'Xem danh sách mã giảm giá',
        'Thêm mã giảm giá',
        'Chỉnh sửa mã giảm giá',
        'Xóa mã giảm giá',
        'Xem báo cáo thống kê',
        'Xem danh sách khách hàng',
        'Thêm mới khách hàng',
        'Chỉnh sửa thông tin khách hàng',
        'Xóa thông tin khách hàng',
        'Thay đổi mật khẩu',
        'Đăng ký tài khoản',
        'Đăng nhập tài khoản',
        'Thêm sản phẩm vào mục yêu thích',
        'Xem danh sách thông báo',
        'Gửi thông báo đến người dùng',
        'Xóa thông báo',
        'Xem phản hồi của khách hàng',
        'Phản hồi lại đánh giá của khách hàng',
        'Thanh toán',
    ]
];
