<?php
return [
    'Permission' => [
        'view_users',
        'add_users',
        'edit_users',
        'delete_users',
        'view_permissions',
        'assign_permissions',
        'view_orders',
        'edit_orders',
        'delete_orders',
        'view_products',
        'add_products',
        'edit_products',
        'delete_products',
        'view_categories',
        'add_categories',
        'edit_categories',
        'delete_categories',
        'view_discounts',
        'add_discounts',
        'edit_discounts',
        'delete_discounts',
        'view_reports',
        'view_customers',
        'add_customers',
        'edit_customers',
        'delete_customers',
        'edit_profile',
        'change_password',
        'place_order',
        'wishlist',
        'view_notifications',
        'send_notification',
        'delete_notifications',
        'view_feedback',
        'reply_feedback',
        'register',
        'login',
    ],
    'Description' =>[
        'Xem danh sách người dùng',
        'Thêm người dùng mới',
        'Chỉnh sửa thôgn tin người dùng',
        'Xóa người dùng',
        'Xem danh sách quyền',
        'Cấp quyền cho người dùng',
        'Xem danh sách đơn hàng',
        'Cập nhật trạng thái đơn hàng',
        'Hủy đơn hàng',
        'Xem danh sách sản phẩm',
        'Thêm sản phẩm mới',
        'Chỉnh sửa sản phẩm',
        'Xóa sản phẩm',
        'Xem danh mục loại sản phẩm',
        'Thêm loại sản phẩm',
        'Chỉnh sửa loại sản phẩm',
        'Xóa loại sản phẩm',
        'Xem danh sách mã giảm giá',
        'Thêm mã giảm giá',
        'Chỉnh sửa mã giảm giá',
        'Xóa mã giảm giá',
        'Xem báo cáo thống kê',
        'Xem danh sách khách hàng',
        'Thêm mới khách hàng',
        'Chỉnh sửa thông tin khách hàng',
        'Xóa thông tin khách hàng',
        'Chỉnh sửa hồ sơ cá nhân',
        'Thay đổi mật khẩu',
        'Đặt hàng',
        'Thêm sản phẩm vào mục yêu thích',
        'Xem danh sách thông báo',
        'Gửi thông báo đến người dùng',
        'Xóa thông báo',
        'Xem phản hồi của khách hàng',
        'Phản hồi lại đánh giá của khách hàng',
        'Đăng ký tài khoản',
        'Đăng nhập tài khoản'
    ]
];
